name: pharmafinderadmin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  flutter_launcher_icons: ^0.14.4
  cloud_functions: ^6.0.0
  csv: ^6.0.0
  file_picker: ^10.3.2
  provider: ^6.1.5+1
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
